SET SERVEROUTPUT ON 

CREATE TABLE TIENDAS 
(
    CODIGO VARCHAR2 (10) NOT NULL,
    NOMBRE VARCHAR2 (20) UNIQUE,
    POBLACION VARCHAR2 (20),
    CATEGORIAS VARCHAR2 (20),
    CODPOSTAL NUMBER (5),
    CONSTRAINT PK_TIENDAS PRIMARY KEY (CODIGO),
    CONSTRAINT CH_TIENDANOMBRE CHECK (REGEXP_LIKE(NOMBRE,'^([[:alpha:]])+$'))
);

CREATE TABLE VENDEDORES
(
    CODIGO VARCHAR2 (3),
    NOMBRE VARCHAR2 (15),
    PAIS VARCHAR2 (20),
    CONSTRAINT PK_VENDEDORES PRIMARY KEY (CODIGO),
    CONSTRAINT CH_VENDEDORPAIS CHECK (PAIS LIKE UPPER(PAIS))
);

